#!/usr/bin/env python3

import os, os.path
import re
import subprocess
import sys

PIPSI_BIN_DIR=os.path.expanduser('~/.local/venvs/')
RXP_PACKAGES = re.compile(r'^\s*Package\s+"([a-zA-Z0-9_.-]+)"')

def gather_packages():
    proc = subprocess.run(['pipsi', 'list'], stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)

    packages = []
    for line in proc.stdout.decode().splitlines():
        match = RXP_PACKAGES.search(line)
        if match:
            packages.append(match.group(1))

    packages.sort()
    return packages

def package_python_version(package):
    package_bin_dir = os.path.join(PIPSI_BIN_DIR, package, 'bin')
    python_bin = os.path.join(package_bin_dir, 'python')

    python_version = None
    if os.path.islink(python_bin):
        python_version = os.readlink(python_bin).replace('python', '')[0]

    if not python_version:
        for ver in ('2.6', '2.7', '3.0', '3.1', '3.2', '3.3', '3.4', '3.5'):
            if os.path.exists(os.path.join(package_bin_dir, 'python%s' % ver)):
                python_version = ver[0]
                break

    if not python_version:
        for ver in ('2', '3'):
            if os.path.exists(os.path.join(package_bin_dir, 'python%s' % ver)):
                python_version = ver
                break

    return python_version

def main():
    packages = gather_packages()
    for package in packages:
        if package == 'pipsi':
            continue

        python_version = package_python_version(package)
        print("Reinstalling %s with python%s" % (package, python_version))
        subprocess.run(['pipsi', 'uninstall', '--yes', package], stdout=sys.stdout, stderr=sys.stderr, stdin=sys.stdin, check=True)
        subprocess.run(['pipsi', 'install', '--python', 'python%s' % python_version, package], stdout=sys.stdout, stderr=sys.stderr, stdin=sys.stdin, check=True)
        print()

if __name__ == '__main__':
    main()
